name: anim
channels:
  - conda-forge

dependencies:
  - python>=3.9
  - setuptools-scm   # automatic project numbering
  - ipykernel
  - pip

  - matplotlib
  # - cartopy
  - shapely

  - numpy
  - pandas
  - xarray
  - zarr

  - dask
  - distirbuted
  # - PyYAML
  # - netCDF4
