name: anim_dev
channels:
  - conda-forge

dependencies:
  - python>=3.9
  - setuptools-scm   # automatic project numbering
  - ipykernel        # if you want jupyter to see your env
  - pip

  - matplotlib
  - cartopy
  # - cartopy_offlinedata
  - shapely

  - numpy
  - scipy
  - pandas
  - xarray
  - zarr

  - ffmpeg

  - dask
  - distributed
  # - PyYAML
  # - netCDF4

  #### tests
  - pytest
  - pytest-cov
  - pytest-mpl

  #### doc
  - sphinx
  - pydata-sphinx-theme
  - sphinx-gallery
  - sphinx-design
  - sphinxcontrib-video

  #### dev
  - black
  - flake8
  - isort
  - pre-commit
  - ruff
  # - pip:
  #   -
